// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TpSignalR.Repositorio;

#nullable disable

namespace TpSignalR.Web.Migrations
{
    [DbContext(typeof(InicializacionContext))]
    partial class InicializacionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TpSignalR.Entidades.Comercio", b =>
                {
                    b.Property<int>("ComercioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComercioId"));

                    b.Property<string>("CategoriasMenu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreciosMenu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("ComercioId");

                    b.ToTable("Comercios");
                });

            modelBuilder.Entity("TpSignalR.Entidades.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("int");

                    b.Property<int?>("ComercioId1")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("HoraEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("int");

                    b.Property<int?>("RepartidorId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioFinalId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioFinalId1")
                        .HasColumnType("int");

                    b.HasKey("PedidoId");

                    b.HasIndex("ComercioId");

                    b.HasIndex("ComercioId1");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("RepartidorId1");

                    b.HasIndex("UsuarioFinalId");

                    b.HasIndex("UsuarioFinalId1");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TpSignalR.Entidades.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PedidoDetalle");
                });

            modelBuilder.Entity("TpSignalR.Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ComercioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("TpSignalR.Entidades.Repartidor", b =>
                {
                    b.Property<int>("RepartidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepartidorId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("LatitudActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LongitudActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RepartidorId");

                    b.ToTable("Repartidores");
                });

            modelBuilder.Entity("TpSignalR.Entidades.UsuarioFinal", b =>
                {
                    b.Property<int>("UsuarioFinalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioFinalId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pedido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UsuarioFinalId");

                    b.ToTable("UsuariosFinales");
                });

            modelBuilder.Entity("TpSignalR.Entidades.Pedido", b =>
                {
                    b.HasOne("TpSignalR.Entidades.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TpSignalR.Entidades.Comercio", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("ComercioId1");

                    b.HasOne("TpSignalR.Entidades.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TpSignalR.Entidades.Repartidor", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("RepartidorId1");

                    b.HasOne("TpSignalR.Entidades.UsuarioFinal", "UsuarioFinal")
                        .WithMany()
                        .HasForeignKey("UsuarioFinalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TpSignalR.Entidades.UsuarioFinal", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioFinalId1");

                    b.Navigation("Comercio");

                    b.Navigation("Repartidor");

                    b.Navigation("UsuarioFinal");
                });

            modelBuilder.Entity("TpSignalR.Entidades.PedidoDetalle", b =>
                {
                    b.HasOne("TpSignalR.Entidades.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TpSignalR.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TpSignalR.Entidades.Producto", b =>
                {
                    b.HasOne("TpSignalR.Entidades.Comercio", "Comercio")
                        .WithMany("Productos")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("TpSignalR.Entidades.Comercio", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TpSignalR.Entidades.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("TpSignalR.Entidades.Repartidor", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TpSignalR.Entidades.UsuarioFinal", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
